In [1]:
import numpy as np

#create an array object
a = np.array([[1, 2, 3], [4, 5 ,6]])

In [2]:
print(a)

[[1 2 3]
 [4 5 6]]


In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
print("No of dimensions : ", a.ndim)

No of dimensions :  2


In [5]:
print("Shape of array: ", a.shape)

Shape of array:  (2, 3)


### Array Creation Techniques

In [7]:
# creating fom a tuple
b = np.array((1, 2, 3))
print(b)

[1 2 3]


In [8]:
# 4x5 array with zeros
z = np.zeros((4, 5))
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
# array with random values
r = np.random.random((3, 3))
print(r)

[[0.54700849 0.85450279 0.99414289]
 [0.47271886 0.23712102 0.6081818 ]
 [0.0569279  0.60170348 0.70575226]]


In [11]:
# Create a sequence
array1 = np.arange(0, 50, 5)
print(array1)

[ 0  5 10 15 20 25 30 35 40 45]


In [16]:
array2 = np.linspace(4, 5 ,5)
print(array2)

[4.   4.25 4.5  4.75 5.  ]


In [17]:
# reshaping an array
# Reshaping 3x4 array into 2x2x3 array
array3 = np.array([[1, 2, 3 ,4], [2, 3, 4, 5], [5, 6, 7, 8]])
print(array3)

[[1 2 3 4]
 [2 3 4 5]
 [5 6 7 8]]


In [18]:
new = array3.reshape(2, 2, 3)

In [19]:
print(new)

[[[1 2 3]
  [4 2 3]]

 [[4 5 5]
  [6 7 8]]]


In [20]:
# flatten array
flarr = array3.flatten()
print(flarr)

[1 2 3 4 2 3 4 5 5 6 7 8]
