In [1]:
import numpy as np

a = np.arange(10)**2
print(a)

[ 0  1  4  9 16 25 36 49 64 81]


### Indexing & Slicing

In [2]:
a[1]

1

In [4]:
a[1:6]

array([ 1,  4,  9, 16, 25], dtype=int32)

In [5]:
a[-1]

81

In [6]:
# iterate over the array
for i in a:
    print(i)

0
1
4
9
16
25
36
49
64
81


In [7]:
# Mean
np.mean(a)

28.5

In [8]:
# Standard Deviation
np.std(a)

26.852374196707448

In [9]:
np.var(a)

721.05

In [10]:
np.max(a)

81

In [13]:
# Iterate over n-dimensional array

# Create a n-dim array
array = np.random.random((4, 4, 4))
print(array)

[[[0.19113921 0.15098437 0.53235691 0.99092251]
  [0.46625165 0.81012404 0.33901377 0.67870574]
  [0.18912883 0.30273784 0.8931358  0.94874298]
  [0.59096867 0.58351412 0.77462045 0.83065322]]

 [[0.95691769 0.29865641 0.91325175 0.40238418]
  [0.06219032 0.7429933  0.83321965 0.64669539]
  [0.6302197  0.84727875 0.13125878 0.2838107 ]
  [0.19607958 0.54289026 0.79830382 0.30298777]]

 [[0.63776901 0.94663976 0.78069295 0.61813763]
  [0.33073759 0.04524076 0.34888826 0.02545962]
  [0.46781681 0.46342492 0.15369687 0.27116926]
  [0.18468686 0.36448828 0.98522924 0.71398492]]

 [[0.70656456 0.45330925 0.6242567  0.77677141]
  [0.26017814 0.03535511 0.45100772 0.65030459]
  [0.72912876 0.4827262  0.23814616 0.16640544]
  [0.30382714 0.44183826 0.56372915 0.27340364]]]


In [12]:
for row in array:
    print(np.mean(row))

0.6276308381884065
0.40333426598376004
0.4291457803943364
0.15790836979382142
